apiVersion: batch/v1
kind: CronJob
metadata:
  name: alias-computation
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alias-computation
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
            args:
              # TODO(michaelkedar): single source of truth w/ terraform config
              - "--bucket=osv-test-vulnerabilities"
