apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: "oss-vdb-test"
            - name: BACKUP_BUCKET
              value: "osv-test-backup"
            - name: AFFECTED_COMMITS_BACKUP_BUCKET
              value: "osv-test-affected-commits"