apiVersion: batch/v1
kind: CronJob
metadata:
  name: combine-to-osv
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: combine-to-osv
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
            - name: INPUT_GCS_BUCKET
              value: osv-test-cve-osv-conversion
            - name: OUTPUT_GCS_BUCKET
              value: osv-test-cve-osv-conversion
