apiVersion: batch/v1
kind: CronJob
metadata:
  name: debian-cve-convert
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          containers:
          - name: debian-cve-convert
            image: debian-cve-convert
            imagePullPolicy: Always
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
            - name: OUTPUT_GCS_BUCKET
              value: osv-test-cve-osv-conversion
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 1
                memory: "1G"
              limits:
                cpu: 1
                memory: "2G"
          restartPolicy: OnFailure
          volumes:
            - name: "ssd"
              hostPath:
                path: "/mnt/disks/ssd0"
