apiVersion: batch/v1
kind: CronJob
metadata:
  name: debian-copyright-mirror
  labels:
    cronLastSuccessfulTimeMins: 2880
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: debian-copyright-mirror
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
            - name: GCS_PATH
              value: gs://osv-test-cve-osv-conversion/debian_copyright/debian_copyright.tar
