apiVersion: batch/v1
kind: CronJob
metadata:
  name: debian-convert
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: debian-convert
            env:
            - name: OUTPUT_GCS_BUCKET
              value: osv-test-debian-osv
