apiVersion: batch/v1
kind: CronJob
metadata:
  name: exporter
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: exporter
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
            args:
              # TODO(michaelkedar): single source of truth w/ terraform config
              - "--uploadToGCS=true"
              - "--num_workers=400"
              - "--bucket=osv-test-vulnerabilities"
              - "--osv_vulns_bucket=osv-test-vulnerabilities"

