apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-sitemap
  labels:
    cronLastSuccessfulTimeMins: 2880
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: generate-sitemap-cron
            env:
            - name: BASE_URL
              value: "https://test.osv.dev"
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
            - name: OUTPUT_GCS_BUCKET
              value: test-osv-dev-sitemap
