apiVersion: batch/v1
kind: CronJob
metadata:
  name: importer-deleter
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: importer-deleter
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
              # TODO(michaelkedar): ssh secrets
              # TODO(michaelkedar): single source of truth w/ terraform config
            args: ["--delete", "--deletion_threshold=10", "--public_log_bucket=osv-test-public-import-logs"]
