apiVersion: batch/v1
kind: CronJob
metadata:
  name: importer
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: importer
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
            args:
              # TODO(michaelkedar): ssh secrets
              # TODO(michaelkedar): single source of truth w/ terraform config
              - "--public_log_bucket=osv-test-public-import-logs"
              # Note that with https://github.com/google/osv.dev/pull/2766
              # addition per-repository settings make this *really* take effect, see
              # https://github.com/google/osv.dev/pull/2837
              - "--strict_validation"
