resources:
- ../../base
- base_nvd-cve-osv.yaml  # TODO: delete when we add this to production
patches:
- workers.yaml
- scaler.yaml
- importer.yaml
- exporter.yaml
- alpine-cve-convert.yaml
- combine-to-osv.yaml
- debian-convert.yaml
- debian-first-version.yaml
- debian-copyright-mirror.yaml
- gen-cperepos-map.yaml
- nvd-cve-osv.yaml
