apiVersion: batch/v1
kind: CronJob
metadata:
  name: nvd-mirror
  labels:
    cronLastSuccessfulTimeMins: 240
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nvd-mirror
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb-test
            - name: BUCKET
              value: osv-test-cve-osv-conversion
