apiVersion: batch/v1
kind: CronJob
metadata:
  name: alpine-cve-convert
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alpine-cve-convert
            env:
            - name: OUTPUT_GCS_BUCKET
              value: cve-osv-conversion
