apiVersion: batch/v1
kind: CronJob
metadata:
  name: debian-copyright-mirror
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: debian-copyright-mirror
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb
            - name: GCS_PATH
              value: gs://cve-osv-conversion/debian_copyright/debian_copyright.tar
