apiVersion: batch/v1
kind: CronJob
metadata:
  name: debian-cve-convert
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: debian-cve-convert
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb
            - name: OUTPUT_GCS_BUCKET
              value: cve-osv-conversion