apiVersion: batch/v1
kind: CronJob
metadata:
  name: exporter
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: exporter
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb
            args:
              - "--upload-to-gcs=true"
              - "--workers=400"
              - "--bucket=osv-vulnerabilities"
              - "--osv-vulns-bucket=osv-vulnerabilities"

