apiVersion: batch/v1
kind: CronJob
metadata:
  name: exporter
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: exporter
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb
            args:
              - "--local=false"
              - "--bucket=osv-vulnerabilities"
              - "--osv_vulns_bucket=osv-vulnerabilities"

