apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-sitemap
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: generate-sitemap-cron
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb
            args:
              - "--base-url=https://osv.dev"
              - "--osv-vulns-bucket=osv-vulnerabilities"
              - "--upload-to-gcs=true"
              - "--bucket=osv-dev-sitemap"

