apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-sitemap
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: generate-sitemap-cron
            env:
            - name: BASE_URL
              value: "https://osv.dev"
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb
            - name: OUTPUT_GCS_BUCKET
              value: osv-dev-sitemap
