apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitter
spec:
  template:
    spec:
      containers:
      - name: gitter
        args:
          - "--port=8888"
          - "--work-dir=/work/gitter"
          - "--fetch-timeout=1h"
        env:
          - name: GOOGLE_CLOUD_PROJECT
            value: oss-vdb
