apiVersion: batch/v1
kind: CronJob
metadata:
  name: importer
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: importer
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb
            - name: OSV_VULNERABILITIES_BUCKET
              value: osv-vulnerabilities
