apiVersion: batch/v1
kind: CronJob
metadata:
  name: importer
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: importer
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb
            args:
              - "--ssh_key_public=/secrets/ssh.pub"
              - "--ssh_key_private=/secrets/ssh"
              - "--public_log_bucket=osv-public-import-logs"
            volumeMounts:
              - mountPath: "/secrets"
                name: "secrets"
          volumes:
          - name: secrets
            secret:
              items:
              - key: ssh
                mode: 384
                path: ssh
              - key: ssh.pub
                path: ssh.pub
              secretName: secrets
