apiVersion: batch/v1
kind: CronJob
metadata:
  name: importer-deleter
spec:
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: importer-deleter
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb
            image: importer
            args:
              - --delete
              - --delete_threshold_pct=20
              - --public_log_bucket=osv-public-import-logs
