apiVersion: batch/v1
kind: CronJob
metadata:
  name: nvd-mirror
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nvd-mirror
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb
            - name: BUCKET
              value: cve-osv-conversion
