apiVersion: batch/v1
kind: CronJob
metadata:
  name: relations
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: relations
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: oss-vdb
            - name: OSV_VULNERABILITIES_BUCKET
              value: osv-vulnerabilities
            - name: OSV_FAILED_TASKS_TOPIC
              value: failed-tasks
