apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers-cves
spec:
  template:
    spec:
      containers:
      - name: workers-cves
        env:
          - name: GOOGLE_CLOUD_PROJECT
            value: oss-vdb
          - name: OSV_VULNERABILITIES_BUCKET
            value: osv-vulnerabilities
