// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.
//
// Despite the above, this required hand-editing to be functional :-(
//
// - https://github.com/omissis/go-jsonschema/issues/159#issuecomment-1820823075
// - https://github.com/omissis/go-jsonschema/issues/171
//
// Generated with:
// go-jsonschema -p cves \
//	--capitalization NVD \
//	--capitalization CVE \
//	--capitalization CPE \
//	--capitalization CVSS \
//	--capitalization ID \
//	--capitalization CISA \
//	--capitalization API \
//	--capitalization JSON \
//	cve_api_json_2.0.schema

package cves

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/atombender/go-jsonschema/pkg/types"
	"github.com/google/osv/vulnfeeds/cvss20"
	"github.com/google/osv/vulnfeeds/cvss30"
	"github.com/google/osv/vulnfeeds/cvss31"
)

type Config struct {
	Operator string `json:"operator,omitempty" yaml:"operator,omitempty" mapstructure:"operator,omitempty"`
	Negate   bool   `json:"negate,omitempty" yaml:"negate,omitempty" mapstructure:"negate,omitempty"`
	Nodes    []Node `json:"nodes" yaml:"nodes" mapstructure:"nodes"`
}

// CPE match string or range
type CPEMatch struct {
	// Criteria corresponds to the JSON schema field "criteria".
	Criteria string `json:"criteria" yaml:"criteria" mapstructure:"criteria"`

	// MatchCriteriaId corresponds to the JSON schema field "matchCriteriaId".
	MatchCriteriaId string `json:"matchCriteriaId" yaml:"matchCriteriaId" mapstructure:"matchCriteriaId"`

	// VersionEndExcluding corresponds to the JSON schema field "versionEndExcluding".
	VersionEndExcluding *string `json:"versionEndExcluding,omitempty" yaml:"versionEndExcluding,omitempty" mapstructure:"versionEndExcluding,omitempty"`

	// VersionEndIncluding corresponds to the JSON schema field "versionEndIncluding".
	VersionEndIncluding *string `json:"versionEndIncluding,omitempty" yaml:"versionEndIncluding,omitempty" mapstructure:"versionEndIncluding,omitempty"`

	// VersionStartExcluding corresponds to the JSON schema field
	// "versionStartExcluding".
	VersionStartExcluding *string `json:"versionStartExcluding,omitempty" yaml:"versionStartExcluding,omitempty" mapstructure:"versionStartExcluding,omitempty"`

	// VersionStartIncluding corresponds to the JSON schema field
	// "versionStartIncluding".
	VersionStartIncluding *string `json:"versionStartIncluding,omitempty" yaml:"versionStartIncluding,omitempty" mapstructure:"versionStartIncluding,omitempty"`

	// Vulnerable corresponds to the JSON schema field "vulnerable".
	Vulnerable bool `json:"vulnerable" yaml:"vulnerable" mapstructure:"vulnerable"`
}

// Vexingly, the timestamps used are not RFC 3339, but part of the (much) broader ISO 8601.
const NVDISO8601Time = "2006-01-02T15:04:05.999"

type NVDTime struct {
	time.Time
}

func (t *NVDTime) UnmarshalJSON(b []byte) (err error) {
	s := strings.Trim(string(b), "\"")
	if s == "null" {
		t.Time = time.Time{}
		return
	}
	t.Time, err = time.Parse(NVDISO8601Time, s)
	return
}

type CVEAPIJSON20Schema struct {
	// Format corresponds to the JSON schema field "format".
	Format string `json:"format" yaml:"format" mapstructure:"format"`

	// ResultsPerPage corresponds to the JSON schema field "resultsPerPage".
	ResultsPerPage int `json:"resultsPerPage" yaml:"resultsPerPage" mapstructure:"resultsPerPage"`

	// StartIndex corresponds to the JSON schema field "startIndex".
	StartIndex int `json:"startIndex" yaml:"startIndex" mapstructure:"startIndex"`

	// Timestamp corresponds to the JSON schema field "timestamp".
	Timestamp NVDTime `json:"timestamp" yaml:"timestamp" mapstructure:"timestamp"`

	// TotalResults corresponds to the JSON schema field "totalResults".
	TotalResults int `json:"totalResults" yaml:"totalResults" mapstructure:"totalResults"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`

	// NVD feed array of CVE
	Vulnerabilities []DefCveItem `json:"vulnerabilities" yaml:"vulnerabilities" mapstructure:"vulnerabilities"`
}

type CVEID string

type CVEItem struct {
	// CISAActionDue corresponds to the JSON schema field "cisaActionDue".
	CISAActionDue *types.SerializableDate `json:"cisaActionDue,omitempty" yaml:"cisaActionDue,omitempty" mapstructure:"cisaActionDue,omitempty"`

	// CISAExploitAdd corresponds to the JSON schema field "cisaExploitAdd".
	CISAExploitAdd *types.SerializableDate `json:"cisaExploitAdd,omitempty" yaml:"cisaExploitAdd,omitempty" mapstructure:"cisaExploitAdd,omitempty"`

	// CISARequiredAction corresponds to the JSON schema field "cisaRequiredAction".
	CISARequiredAction *string `json:"cisaRequiredAction,omitempty" yaml:"cisaRequiredAction,omitempty" mapstructure:"cisaRequiredAction,omitempty"`

	// CISAVulnerabilityName corresponds to the JSON schema field
	// "cisaVulnerabilityName".
	CISAVulnerabilityName *string `json:"cisaVulnerabilityName,omitempty" yaml:"cisaVulnerabilityName,omitempty" mapstructure:"cisaVulnerabilityName,omitempty"`

	// Configurations corresponds to the JSON schema field "configurations".
	Configurations []Config `json:"configurations,omitempty" yaml:"configurations,omitempty" mapstructure:"configurations,omitempty"`

	// Descriptions corresponds to the JSON schema field "descriptions".
	Descriptions []LangString `json:"descriptions" yaml:"descriptions" mapstructure:"descriptions"`

	// EvaluatorComment corresponds to the JSON schema field "evaluatorComment".
	EvaluatorComment *string `json:"evaluatorComment,omitempty" yaml:"evaluatorComment,omitempty" mapstructure:"evaluatorComment,omitempty"`

	// EvaluatorImpact corresponds to the JSON schema field "evaluatorImpact".
	EvaluatorImpact *string `json:"evaluatorImpact,omitempty" yaml:"evaluatorImpact,omitempty" mapstructure:"evaluatorImpact,omitempty"`

	// EvaluatorSolution corresponds to the JSON schema field "evaluatorSolution".
	EvaluatorSolution *string `json:"evaluatorSolution,omitempty" yaml:"evaluatorSolution,omitempty" mapstructure:"evaluatorSolution,omitempty"`

	// ID corresponds to the JSON schema field "id".
	ID CVEID `json:"id" yaml:"id" mapstructure:"id"`

	// LastModified corresponds to the JSON schema field "lastModified".
	LastModified NVDTime `json:"lastModified" yaml:"lastModified" mapstructure:"lastModified"`

	// Metric scores for a vulnerability as found on NVD.
	Metrics *CVEItemMetrics `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`

	// Published corresponds to the JSON schema field "published".
	Published NVDTime `json:"published" yaml:"published" mapstructure:"published"`

	// References corresponds to the JSON schema field "references".
	References []Reference `json:"references" yaml:"references" mapstructure:"references"`

	// SourceIdentifier corresponds to the JSON schema field "sourceIdentifier".
	SourceIdentifier *string `json:"sourceIdentifier,omitempty" yaml:"sourceIdentifier,omitempty" mapstructure:"sourceIdentifier,omitempty"`

	// VendorComments corresponds to the JSON schema field "vendorComments".
	VendorComments []VendorComment `json:"vendorComments,omitempty" yaml:"vendorComments,omitempty" mapstructure:"vendorComments,omitempty"`

	// VulnStatus corresponds to the JSON schema field "vulnStatus".
	VulnStatus *string `json:"vulnStatus,omitempty" yaml:"vulnStatus,omitempty" mapstructure:"vulnStatus,omitempty"`

	// Weaknesses corresponds to the JSON schema field "weaknesses".
	Weaknesses []Weakness `json:"weaknesses,omitempty" yaml:"weaknesses,omitempty" mapstructure:"weaknesses,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VendorComment) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["comment"]; !ok || v == nil {
		return fmt.Errorf("field comment in VendorComment: required")
	}
	if v, ok := raw["lastModified"]; !ok || v == nil {
		return fmt.Errorf("field lastModified in VendorComment: required")
	}
	if v, ok := raw["organization"]; !ok || v == nil {
		return fmt.Errorf("field organization in VendorComment: required")
	}
	type Plain VendorComment
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = VendorComment(plain)
	return nil
}

// CVSS V2.0 score. (hand-generated)
type CVSSV2 struct {
	Source                  string         `json:"source" yaml:"source" mapstructure:"source"`
	Type                    string         `json:"type" yaml:"type" mapstructure:"type"`
	BaseSeverity            string         `json:"baseSeverity,omitempty" yaml:"baseSeverity,omitempty" mapstructure:"baseSeverity,omitempty"`
	CVSSData                cvss20.CVSSV20 `json:"cvssData" yaml:"cvssData" mapstructure:"cvssData"`
	ExploitabilityScore     DefSubscore    `json:"exploitabilityScore,omitempty" yaml:"exploitabilityScore,omitempty" mapstructure:"exploitabilityScore,omitempty"`
	ImpactScore             DefSubscore    `json:"impactScore,omitempty" yaml:"impactScore,omitempty" mapstructure:"impactScore,omitempty"`
	AcInsufInfo             bool           `json:"acInsufInfo,omitempty" yaml:"acInsufInfo,omitempty" mapstructure:"acInsufInfo,omitempty"`
	ObtainAllPrivilege      bool           `json:"obtainAllPrivilege,omitempty" yaml:"obtainAllPrivilege,omitempty" mapstructure:"obtainAllPrivilege,omitempty"`
	ObtainUserPrivilege     bool           `json:"obtainUserPrivilege,omitempty" yaml:"obtainUserPrivilege,omitempty" mapstructure:"obtainUserPrivilege,omitempty"`
	ObtainOtherPrivilege    bool           `json:"obtainOtherPrivilege,omitempty" yaml:"obtainOtherPrivilege,omitempty" mapstructure:"obtainOtherPrivilege,omitempty"`
	UserInteractionRequired bool           `json:"userInteractionRequired,omitempty" yaml:"userInteractionRequired,omitempty" mapstructure:"userInteractionRequired,omitempty"`
}

// CVSS V3.0 score. (hand-generated)
type CVSSV30 struct {
	Source              string         `json:"source" yaml:"source" mapstructure:"source"`
	Type                string         `json:"type" yaml:"type" mapstructure:"type"`
	CVSSData            cvss30.CVSSV30 `json:"cvssData" yaml:"cvssData" mapstructure:"cvssData"`
	ExploitabilityScore *DefSubscore   `json:"exploitabilityScore,omitempty" yaml:"exploitabilityScore,omitempty" mapstructure:"exploitabilityScore,omitempty"`
	ImpactScore         *DefSubscore   `json:"impactScore,omitempty" yaml:"impactScore,omitempty" mapstructure:"impactScore,omitempty"`
}

// CVSS V3.1 score. (hand-generated)
type CVSSV31 struct {
	Source              string `json:"source" yaml:"source" mapstructure:"source"`
	Type                string `json:"type" yaml:"type" mapstructure:"type"`
	CVSSData            cvss31.CVSSV31
	ExploitabilityScore *DefSubscore `json:"exploitabilityScore,omitempty" yaml:"exploitabilityScore,omitempty" mapstructure:"exploitabilityScore,omitempty"`
	ImpactScore         *DefSubscore `json:"impactScore,omitempty" yaml:"impactScore,omitempty" mapstructure:"impactScore,omitempty"`
}

// Metric scores for a vulnerability as found on NVD.
type CVEItemMetrics struct {
	// CVSS V2.0 score.
	CVSSMetricV2 []CVSSV2 `json:"cvssMetricV2,omitempty" yaml:"cvssMetricV2,omitempty" mapstructure:"cvssMetricV2,omitempty"`

	// CVSS V3.0 score.
	CVSSMetricV30 []CVSSV30 `json:"cvssMetricV30,omitempty" yaml:"cvssMetricV30,omitempty" mapstructure:"cvssMetricV30,omitempty"`

	// CVSS V3.1 score.
	CVSSMetricV31 []CVSSV31 `json:"cvssMetricV31,omitempty" yaml:"cvssMetricV31,omitempty" mapstructure:"cvssMetricV31,omitempty"`
}

type Reference struct {
	// Source corresponds to the JSON schema field "source".
	Source string `json:"source,omitempty" yaml:"source,omitempty" mapstructure:"source,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// Url corresponds to the JSON schema field "url".
	Url string `json:"url" yaml:"url" mapstructure:"url"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Reference) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["url"]; !ok || v == nil {
		return fmt.Errorf("field url in Reference: required")
	}
	type Plain Reference
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if len(plain.Url) > 500 {
		return fmt.Errorf("field %s length: must be <= %d", "url", 500)
	}
	*j = Reference(plain)
	return nil
}

type VendorComment struct {
	// Comment corresponds to the JSON schema field "comment".
	Comment string `json:"comment" yaml:"comment" mapstructure:"comment"`

	// LastModified corresponds to the JSON schema field "lastModified".
	LastModified NVDTime `json:"lastModified" yaml:"lastModified" mapstructure:"lastModified"`

	// Organization corresponds to the JSON schema field "organization".
	Organization string `json:"organization" yaml:"organization" mapstructure:"organization"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LangString) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["lang"]; !ok || v == nil {
		return fmt.Errorf("field lang in LangString: required")
	}
	if v, ok := raw["value"]; !ok || v == nil {
		return fmt.Errorf("field value in LangString: required")
	}
	type Plain LangString
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	// CVE-2020-35800 runs afoul of this (see https://github.com/omissis/go-jsonschema/issues/155#issuecomment-1823970902)
	// if len(plain.Value) > 4096 {
	// 	return fmt.Errorf("field %s length: must be <= %d, have %d with content %q", "value", 4096, len(plain.Value), plain.Value)
	// }
	*j = LangString(plain)
	return nil
}

type Weakness interface{}

type LangString struct {
	// Lang corresponds to the JSON schema field "lang".
	Lang string `json:"lang" yaml:"lang" mapstructure:"lang"`

	// Value corresponds to the JSON schema field "value".
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CVEItem) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["descriptions"]; !ok || v == nil {
		return fmt.Errorf("field descriptions in CveItem: required")
	}
	if v, ok := raw["id"]; !ok || v == nil {
		return fmt.Errorf("field id in CveItem: required")
	}
	if v, ok := raw["lastModified"]; !ok || v == nil {
		return fmt.Errorf("field lastModified in CveItem: required")
	}
	if v, ok := raw["published"]; !ok || v == nil {
		return fmt.Errorf("field published in CveItem: required")
	}
	if v, ok := raw["references"]; !ok || v == nil {
		return fmt.Errorf("field references in CveItem: required")
	}
	type Plain CVEItem
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	if plain.Descriptions != nil && len(plain.Descriptions) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "descriptions", 1)
	}
	if len(plain.References) > 500 {
		return fmt.Errorf("field %s length: must be <= %d", "references", 500)
	}
	*j = CVEItem(plain)
	return nil
}

// (hand generated).
type DefCveItem struct {
	CVE CVEItem `json:"cve" yaml:"cve" mapstructure:"cve"`
}

// CVSS subscore.
type DefSubscore float64

// Defines a configuration node in an NVD applicability statement.
type Node struct {
	Operator string     `json:"operator" yaml:"operator" mapstructure:"operator"`
	Negate   bool       `json:"negate,omitempty" yaml:"negate,omitempty" mapstructure:"negate,omitempty"`
	CPEMatch []CPEMatch `json:"cpeMatch" yaml:"cpeMatch" mapstructure:"cpeMatch"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CPEMatch) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["criteria"]; !ok || v == nil {
		return fmt.Errorf("field criteria in CPEMatch: required")
	}
	if v, ok := raw["matchCriteriaId"]; !ok || v == nil {
		return fmt.Errorf("field matchCriteriaId in CPEMatch: required")
	}
	if v, ok := raw["vulnerable"]; !ok || v == nil {
		return fmt.Errorf("field vulnerable in CPEMatch: required")
	}
	type Plain CPEMatch
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CPEMatch(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CVEAPIJSON20Schema) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["format"]; !ok || v == nil {
		return fmt.Errorf("field format in CVEAPIJSON20Schema: required")
	}
	if v, ok := raw["resultsPerPage"]; !ok || v == nil {
		return fmt.Errorf("field resultsPerPage in CVEAPIJSON20Schema: required")
	}
	if v, ok := raw["startIndex"]; !ok || v == nil {
		return fmt.Errorf("field startIndex in CVEAPIJSON20Schema: required")
	}
	if v, ok := raw["timestamp"]; !ok || v == nil {
		return fmt.Errorf("field timestamp in CVEAPIJSON20Schema: required")
	}
	if v, ok := raw["totalResults"]; !ok || v == nil {
		return fmt.Errorf("field totalResults in CVEAPIJSON20Schema: required")
	}
	if v, ok := raw["version"]; !ok || v == nil {
		return fmt.Errorf("field version in CVEAPIJSON20Schema: required")
	}
	if v, ok := raw["vulnerabilities"]; !ok || v == nil {
		return fmt.Errorf("field vulnerabilities in CVEAPIJSON20Schema: required")
	}
	type Plain CVEAPIJSON20Schema
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = CVEAPIJSON20Schema(plain)
	return nil
}
