apiVersion: batch/v1
kind: CronJob
metadata:
  name: importer-deleter
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: importer-deleter
            env:
            - name: GOOGLE_CLOUD_PROJECT
              value: private-osv
            - name: WORKER_TASK_TOPIC
              value: "osv-work"
            image: importer
            args:
              - --delete
              - --delete-threshold-pct=2
