# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: repository.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'repository.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10repository.proto\x12\x06gitter\".\n\x0c\x43ommitDetail\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\x10\n\x08patch_id\x18\x02 \x01(\x0c\"8\n\x0fRepositoryCache\x12%\n\x07\x63ommits\x18\x01 \x03(\x0b\x32\x14.gitter.CommitDetail\"\x16\n\x06\x43ommit\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\"\"\n\x03Ref\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\x0c\"\x82\x01\n\x17\x41\x66\x66\x65\x63tedCommitsResponse\x12\x1f\n\x07\x63ommits\x18\x01 \x03(\x0b\x32\x0e.gitter.Commit\x12\x19\n\x04tags\x18\x02 \x03(\x0b\x32\x0b.gitter.Ref\x12+\n\x14\x63herry_picked_events\x18\x03 \x03(\x0b\x32\r.gitter.Event\"<\n\x05\x45vent\x12%\n\nevent_type\x18\x01 \x01(\x0e\x32\x11.gitter.EventType\x12\x0c\n\x04hash\x18\x02 \x01(\t\"1\n\x0c\x43\x61\x63heRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x14\n\x0c\x66orce_update\x18\x02 \x01(\x08\"\xc5\x01\n\x16\x41\x66\x66\x65\x63tedCommitsRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x1d\n\x06\x65vents\x18\x02 \x03(\x0b\x32\r.gitter.Event\x12%\n\x1d\x64\x65tect_cherrypicks_introduced\x18\x03 \x01(\x08\x12 \n\x18\x64\x65tect_cherrypicks_fixed\x18\x04 \x01(\x08\x12 \n\x18\x64\x65tect_cherrypicks_limit\x18\x05 \x01(\x08\x12\x14\n\x0c\x66orce_update\x18\x06 \x01(\x08*D\n\tEventType\x12\x0e\n\nINTRODUCED\x10\x00\x12\t\n\x05\x46IXED\x10\x01\x12\x11\n\rLAST_AFFECTED\x10\x02\x12\t\n\x05LIMIT\x10\x03\x42\x0eZ\x0c./repositoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'repository_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./repository'
  _globals['_EVENTTYPE']._serialized_start=640
  _globals['_EVENTTYPE']._serialized_end=708
  _globals['_COMMITDETAIL']._serialized_start=28
  _globals['_COMMITDETAIL']._serialized_end=74
  _globals['_REPOSITORYCACHE']._serialized_start=76
  _globals['_REPOSITORYCACHE']._serialized_end=132
  _globals['_COMMIT']._serialized_start=134
  _globals['_COMMIT']._serialized_end=156
  _globals['_REF']._serialized_start=158
  _globals['_REF']._serialized_end=192
  _globals['_AFFECTEDCOMMITSRESPONSE']._serialized_start=195
  _globals['_AFFECTEDCOMMITSRESPONSE']._serialized_end=325
  _globals['_EVENT']._serialized_start=327
  _globals['_EVENT']._serialized_end=387
  _globals['_CACHEREQUEST']._serialized_start=389
  _globals['_CACHEREQUEST']._serialized_end=438
  _globals['_AFFECTEDCOMMITSREQUEST']._serialized_start=441
  _globals['_AFFECTEDCOMMITSREQUEST']._serialized_end=638
# @@protoc_insertion_point(module_scope)
