"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _EventType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EventTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EventType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    INTRODUCED: _EventType.ValueType  # 0
    FIXED: _EventType.ValueType  # 1
    LAST_AFFECTED: _EventType.ValueType  # 2
    LIMIT: _EventType.ValueType  # 3

class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper): ...

INTRODUCED: EventType.ValueType  # 0
FIXED: EventType.ValueType  # 1
LAST_AFFECTED: EventType.ValueType  # 2
LIMIT: EventType.ValueType  # 3
Global___EventType: _TypeAlias = EventType  # noqa: Y015

@_typing.final
class CommitDetail(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HASH_FIELD_NUMBER: _builtins.int
    PATCH_ID_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    patch_id: _builtins.bytes
    def __init__(
        self,
        *,
        hash: _builtins.bytes = ...,
        patch_id: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hash", b"hash", "patch_id", b"patch_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CommitDetail: _TypeAlias = CommitDetail  # noqa: Y015

@_typing.final
class RepositoryCache(_message.Message):
    """RepositoryCache contains only immutable information of a repository (commit hash and the associated patch ID)
    Other git-related structures such as refs and the actual graph are to be constructed when a request comes in.
    """

    DESCRIPTOR: _descriptor.Descriptor

    COMMITS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def commits(self) -> _containers.RepeatedCompositeFieldContainer[Global___CommitDetail]: ...
    def __init__(
        self,
        *,
        commits: _abc.Iterable[Global___CommitDetail] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commits", b"commits"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RepositoryCache: _TypeAlias = RepositoryCache  # noqa: Y015

@_typing.final
class Commit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HASH_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    def __init__(
        self,
        *,
        hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hash", b"hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Commit: _TypeAlias = Commit  # noqa: Y015

@_typing.final
class Ref(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    hash: _builtins.bytes
    def __init__(
        self,
        *,
        label: _builtins.str = ...,
        hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hash", b"hash", "label", b"label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Ref: _TypeAlias = Ref  # noqa: Y015

@_typing.final
class AffectedCommitsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMITS_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    CHERRY_PICKED_EVENTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def commits(self) -> _containers.RepeatedCompositeFieldContainer[Global___Commit]: ...
    @_builtins.property
    def tags(self) -> _containers.RepeatedCompositeFieldContainer[Global___Ref]: ...
    @_builtins.property
    def cherry_picked_events(self) -> _containers.RepeatedCompositeFieldContainer[Global___Event]: ...
    def __init__(
        self,
        *,
        commits: _abc.Iterable[Global___Commit] | None = ...,
        tags: _abc.Iterable[Global___Ref] | None = ...,
        cherry_picked_events: _abc.Iterable[Global___Event] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cherry_picked_events", b"cherry_picked_events", "commits", b"commits", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AffectedCommitsResponse: _TypeAlias = AffectedCommitsResponse  # noqa: Y015

@_typing.final
class Event(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVENT_TYPE_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    event_type: Global___EventType.ValueType
    hash: _builtins.str
    def __init__(
        self,
        *,
        event_type: Global___EventType.ValueType = ...,
        hash: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_type", b"event_type", "hash", b"hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Event: _TypeAlias = Event  # noqa: Y015

@_typing.final
class CacheRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    URL_FIELD_NUMBER: _builtins.int
    FORCE_UPDATE_FIELD_NUMBER: _builtins.int
    url: _builtins.str
    force_update: _builtins.bool
    def __init__(
        self,
        *,
        url: _builtins.str = ...,
        force_update: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["force_update", b"force_update", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CacheRequest: _TypeAlias = CacheRequest  # noqa: Y015

@_typing.final
class AffectedCommitsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    URL_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    DETECT_CHERRYPICKS_INTRODUCED_FIELD_NUMBER: _builtins.int
    DETECT_CHERRYPICKS_FIXED_FIELD_NUMBER: _builtins.int
    DETECT_CHERRYPICKS_LIMIT_FIELD_NUMBER: _builtins.int
    FORCE_UPDATE_FIELD_NUMBER: _builtins.int
    CONSIDER_ALL_BRANCHES_FIELD_NUMBER: _builtins.int
    url: _builtins.str
    detect_cherrypicks_introduced: _builtins.bool
    detect_cherrypicks_fixed: _builtins.bool
    detect_cherrypicks_limit: _builtins.bool
    force_update: _builtins.bool
    consider_all_branches: _builtins.bool
    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[Global___Event]: ...
    def __init__(
        self,
        *,
        url: _builtins.str = ...,
        events: _abc.Iterable[Global___Event] | None = ...,
        detect_cherrypicks_introduced: _builtins.bool = ...,
        detect_cherrypicks_fixed: _builtins.bool = ...,
        detect_cherrypicks_limit: _builtins.bool = ...,
        force_update: _builtins.bool = ...,
        consider_all_branches: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["consider_all_branches", b"consider_all_branches", "detect_cherrypicks_fixed", b"detect_cherrypicks_fixed", "detect_cherrypicks_introduced", b"detect_cherrypicks_introduced", "detect_cherrypicks_limit", b"detect_cherrypicks_limit", "events", b"events", "force_update", b"force_update", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AffectedCommitsRequest: _TypeAlias = AffectedCommitsRequest  # noqa: Y015
