apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "0 18 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: cron
            imagePullPolicy: Always
            command: ["/usr/local/bin/backup/backup.py"]
            resources:
              requests:
                cpu: 1
                memory: "3G"
              limits:
                cpu: 1
                memory: "4G"
          restartPolicy: OnFailure
