apiVersion: batch/v1
kind: CronJob
metadata:
  name: combine-to-osv
  labels:
    cronLastSuccessfulTimeMins: "90"
spec:
  schedule: "30 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          tolerations:
          - key: workloadType
            operator: Equal
            value: highend
          containers:
          - name: combine-to-osv
            image: combine-to-osv
            imagePullPolicy: Always
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: "30"
                memory: "4G"
              limits:
                cpu: "30"
                memory: "8G"
          nodeSelector:
            cloud.google.com/gke-nodepool: highend
          restartPolicy: Never # on the assumption that the next scheduled run is soon enough
          volumes:
            - name: "ssd"
              hostPath:
                path: "/mnt/disks/ssd0"
