apiVersion: batch/v1
kind: CronJob
metadata:
  name: combine-to-osv
spec:
  schedule: "30 */1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          tolerations:
          - key: workloadType
            operator: Equal
            value: highend
          containers:
          - name: combine-to-osv
            image: combine-to-osv
            imagePullPolicy: Always
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 2
                memory: "1G"
              limits:
                cpu: 2
                memory: "2G"
          nodeSelector:
            cloud.google.com/gke-nodepool: highend
          restartPolicy: OnFailure
          volumes:
            - name: "ssd"
              hostPath:
                path: "/mnt/disks/ssd0"
