apiVersion: batch/v1
kind: CronJob
metadata:
  name: cve5-to-osv
  labels:
    cronLastSuccessfulTimeMins: "2160"
spec:
  timeZone: Australia/Sydney
  schedule: "30 5,1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 86400
      template:
        spec:
          containers:
          - name: cve5-to-osv
            image: cve5-to-osv
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "8"
                memory: "64G"
              limits:
                cpu: "12"
                memory: "96G"
            env:
              - name: GITTER_HOST
                value: http://gitter-service:8888
          restartPolicy: Never
          tolerations:
          - key: workloadType
            operator: Equal
            value: highend
          volumes:
            - name: "ssd"
              hostPath:
                path: "/mnt/disks/ssd0"
