apiVersion: batch/v1
kind: CronJob
metadata:
  name: debian-cve-convert
  labels:
    cronLastSuccessfulTimeMins: "120"
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          containers:
          - name: debian-cve-convert
            image: debian-cve-convert
            imagePullPolicy: Always
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: "1"
                memory: "1G"
              limits:
                cpu: "1"
                memory: "2G"
          restartPolicy: Never
          volumes:
            - name: "ssd"
              hostPath:
                path: "/mnt/disks/ssd0"