apiVersion: batch/v1
kind: CronJob
metadata:
  name: debian-cve-convert
  labels:
    cronLastSuccessfulTimeMins: "120"
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          tolerations:
          - key: workloadType
            operator: Equal
            value: highend
          containers:
          - name: debian-cve-convert
            image: debian-cve-convert
            imagePullPolicy: Always
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: "8"
                memory: "8G"
              limits:
                cpu: "16"
                memory: "16G"
          restartPolicy: Never
          volumes:
            - name: "ssd"
              hostPath:
                path: "/mnt/disks/ssd0"
