apiVersion: batch/v1
kind: CronJob
metadata:
  name: debian-convert
  labels:
    cronLastSuccessfulTimeMins: "180"
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          containers:
          - name: debian-convert
            image: debian-convert
            imagePullPolicy: Always
            command:
              - "/src/run_convert_debian.sh"
            volumeMounts:
              - mountPath: "/work"
                name: "ssd"
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 1
                memory: "1G"
              limits:
                cpu: 1
                memory: "2G"
          restartPolicy: OnFailure
          volumes:
            - name: "ssd"
              hostPath:
                path: "/mnt/disks/ssd0"
