apiVersion: batch/v1
kind: CronJob
metadata:
  name: exporter
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  # If the previous job overruns by more than a minute,
  # Don't try to immediately queue up the next job
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
          - key: workloadType
            operator: Equal
            value: highend
          nodeSelector:
            cloud.google.com/gke-nodepool: highend
          containers:
          - name: exporter
            image: exporter
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: "/work"
                name: "ssd"
            resources:
              requests:
                cpu: "6"
                memory: "8G"
              limits:
                cpu: "6"
                memory: "12G"
          restartPolicy: OnFailure
          volumes:
            - name: "ssd"
              emptyDir:
                sizeLimit: 60Gi
