apiVersion: batch/v1
kind: CronJob
metadata:
  name: exporter
  labels:
    cronLastSuccessfulTimeMins: "30"
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  # If the previous job overruns by more than a minute,
  # Don't try to immediately queue up the next job
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
          - key: workloadType
            operator: Equal
            value: highend
          nodeSelector:
            cloud.google.com/gke-nodepool: highend
          containers:
          - name: exporter
            image: exporter
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "12"
                memory: "40Gi"
              limits:
                cpu: "20"
                memory: "64Gi"
          restartPolicy: Never
