apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-sitemap
  labels:
    cronLastSuccessfulTimeMins: "2880"
spec:
  schedule: "30 8 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: generate-sitemap-cron
            image: cron
            imagePullPolicy: Always
            command: ["/usr/local/bin/generate_sitemap/generate_and_upload.sh"]
            resources:
              requests:
                cpu: "1"
                memory: "4G"
              limits:
                cpu: "1"
                memory: "6G"
          restartPolicy: OnFailure
