apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-sitemap
  labels:
    cronLastSuccessfulTimeMins: "2880"
spec:
  schedule: "30 8 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: generate-sitemap-cron
            image: generatesitemap
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "1"
                memory: "4G"
              limits:
                cpu: "1"
                memory: "6G"
            env:
              - name: TRACE_SAMPLE_RATE
                value: "1.0"
          restartPolicy: OnFailure
