apiVersion: batch/v1
kind: CronJob
metadata:
  name: importer
  labels:
    cronLastSuccessfulTimeMins: "90"
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
          - key: workloadType
            operator: Equal
            value: importer-pool
          containers:
          - name: importer
            image: importer
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: "/work"
                name: "ssd"
            env:
              - name: GITTER_HOST
                value: http://gitter-service:8888
              - name: IMPORT_TRACE_SAMPLE_RATE # for the overall importer trace
                value: "1.0"
              - name: TRACE_SAMPLE_RATE # for the individual vulnerability entries
                value: "0.05"
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: "1"
                memory: "24G"
              limits:
                cpu: "2"
                memory: "32G"
          nodeSelector:
            cloud.google.com/gke-nodepool: importer-pool
          restartPolicy: Never
          volumes:
            - name: "ssd"
              hostPath:
                path: "/mnt/disks/ssd0"
