apiVersion: batch/v1
kind: CronJob
metadata:
  name: nvd-cve-osv
  labels:
    cronLastSuccessfulTimeMins: "2160"
spec:
  timeZone: Australia/Sydney
  schedule: "0 6,13 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 86400
      template:
        spec:
          containers:
          - name: nvd-cve-osv
            image: nvd-cve-osv
            imagePullPolicy: Always
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 1
                memory: "2G"
              limits:
                cpu: 1
                memory: "4G"
            env:
              - name: WORK_DIR
                value: /tmp
              - name: FIRST_INSCOPE_YEAR
                value: "2016"
          restartPolicy: Never
          volumes:
            - name: "ssd"
              hostPath:
                path: "/mnt/disks/ssd0"
