apiVersion: batch/v1
kind: CronJob
metadata:
  name: record-checker
  labels:
    cronLastSuccessfulTimeMins: "90"
spec:
  schedule: "10/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: record-checker
            image: record-checker
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "1"
                memory: "1G"
              limits:
                cpu: "1"
                memory: "2G"
            env:
              - name: TRACE_SAMPLE_RATE
                value: "1.0"
          restartPolicy: Never
