# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-private
  template:
    metadata:
      labels:
        name: worker-private
    spec:
      containers:
      - name: worker-private
        image: worker
        imagePullPolicy: Always
        env:
          - name: GITTER_HOST
            value: http://gitter-service:8888
          - name: PUBSUB_SUBSCRIPTION
            value: tasks
          - name: DATASTORE_DATABASE_ID
            value: "" # default
          - name: FAILED_TASKS_TOPIC
            value: failed-tasks
          - name: NOTIFY_PYPI
            value: "false"
        resources:
          requests:
            cpu: 1
            memory: "10G"
          limits:
            cpu: 2
            memory: "13G"
