// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: repository.proto

package repository

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_INTRODUCED    EventType = 0
	EventType_FIXED         EventType = 1
	EventType_LAST_AFFECTED EventType = 2
	EventType_LIMIT         EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "INTRODUCED",
		1: "FIXED",
		2: "LAST_AFFECTED",
		3: "LIMIT",
	}
	EventType_value = map[string]int32{
		"INTRODUCED":    0,
		"FIXED":         1,
		"LAST_AFFECTED": 2,
		"LIMIT":         3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_repository_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_repository_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{0}
}

type CommitDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	PatchId       []byte                 `protobuf:"bytes,2,opt,name=patch_id,json=patchId,proto3" json:"patch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitDetail) Reset() {
	*x = CommitDetail{}
	mi := &file_repository_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDetail) ProtoMessage() {}

func (x *CommitDetail) ProtoReflect() protoreflect.Message {
	mi := &file_repository_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDetail.ProtoReflect.Descriptor instead.
func (*CommitDetail) Descriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{0}
}

func (x *CommitDetail) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CommitDetail) GetPatchId() []byte {
	if x != nil {
		return x.PatchId
	}
	return nil
}

// RepositoryCache contains only immutable information of a repository (commit hash and the associated patch ID)
// Other git-related structures such as refs and the actual graph are to be constructed when a request comes in.
type RepositoryCache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*CommitDetail        `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryCache) Reset() {
	*x = RepositoryCache{}
	mi := &file_repository_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryCache) ProtoMessage() {}

func (x *RepositoryCache) ProtoReflect() protoreflect.Message {
	mi := &file_repository_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryCache.ProtoReflect.Descriptor instead.
func (*RepositoryCache) Descriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{1}
}

func (x *RepositoryCache) GetCommits() []*CommitDetail {
	if x != nil {
		return x.Commits
	}
	return nil
}

type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_repository_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_repository_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{2}
}

func (x *Commit) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Ref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_repository_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_repository_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{3}
}

func (x *Ref) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Ref) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type AffectedCommitsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Commits            []*Commit              `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	Tags               []*Ref                 `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	CherryPickedEvents []*Event               `protobuf:"bytes,3,rep,name=cherry_picked_events,json=cherryPickedEvents,proto3" json:"cherry_picked_events,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AffectedCommitsResponse) Reset() {
	*x = AffectedCommitsResponse{}
	mi := &file_repository_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffectedCommitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffectedCommitsResponse) ProtoMessage() {}

func (x *AffectedCommitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffectedCommitsResponse.ProtoReflect.Descriptor instead.
func (*AffectedCommitsResponse) Descriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{4}
}

func (x *AffectedCommitsResponse) GetCommits() []*Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *AffectedCommitsResponse) GetTags() []*Ref {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AffectedCommitsResponse) GetCherryPickedEvents() []*Event {
	if x != nil {
		return x.CherryPickedEvents
	}
	return nil
}

type TagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Ref                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsResponse) Reset() {
	*x = TagsResponse{}
	mi := &file_repository_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsResponse) ProtoMessage() {}

func (x *TagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repository_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsResponse.ProtoReflect.Descriptor instead.
func (*TagsResponse) Descriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{5}
}

func (x *TagsResponse) GetTags() []*Ref {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     EventType              `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=gitter.EventType" json:"event_type,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_repository_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_repository_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_INTRODUCED
}

func (x *Event) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type CacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ForceUpdate   bool                   `protobuf:"varint,2,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheRequest) Reset() {
	*x = CacheRequest{}
	mi := &file_repository_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRequest) ProtoMessage() {}

func (x *CacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRequest.ProtoReflect.Descriptor instead.
func (*CacheRequest) Descriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{7}
}

func (x *CacheRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CacheRequest) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

type AffectedCommitsRequest struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Url                         string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Events                      []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	DetectCherrypicksIntroduced bool                   `protobuf:"varint,3,opt,name=detect_cherrypicks_introduced,json=detectCherrypicksIntroduced,proto3" json:"detect_cherrypicks_introduced,omitempty"`
	DetectCherrypicksFixed      bool                   `protobuf:"varint,4,opt,name=detect_cherrypicks_fixed,json=detectCherrypicksFixed,proto3" json:"detect_cherrypicks_fixed,omitempty"`
	DetectCherrypicksLimit      bool                   `protobuf:"varint,5,opt,name=detect_cherrypicks_limit,json=detectCherrypicksLimit,proto3" json:"detect_cherrypicks_limit,omitempty"`
	ForceUpdate                 bool                   `protobuf:"varint,6,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	ConsiderAllBranches         bool                   `protobuf:"varint,7,opt,name=consider_all_branches,json=considerAllBranches,proto3" json:"consider_all_branches,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AffectedCommitsRequest) Reset() {
	*x = AffectedCommitsRequest{}
	mi := &file_repository_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffectedCommitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffectedCommitsRequest) ProtoMessage() {}

func (x *AffectedCommitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffectedCommitsRequest.ProtoReflect.Descriptor instead.
func (*AffectedCommitsRequest) Descriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{8}
}

func (x *AffectedCommitsRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AffectedCommitsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *AffectedCommitsRequest) GetDetectCherrypicksIntroduced() bool {
	if x != nil {
		return x.DetectCherrypicksIntroduced
	}
	return false
}

func (x *AffectedCommitsRequest) GetDetectCherrypicksFixed() bool {
	if x != nil {
		return x.DetectCherrypicksFixed
	}
	return false
}

func (x *AffectedCommitsRequest) GetDetectCherrypicksLimit() bool {
	if x != nil {
		return x.DetectCherrypicksLimit
	}
	return false
}

func (x *AffectedCommitsRequest) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

func (x *AffectedCommitsRequest) GetConsiderAllBranches() bool {
	if x != nil {
		return x.ConsiderAllBranches
	}
	return false
}

var File_repository_proto protoreflect.FileDescriptor

const file_repository_proto_rawDesc = "" +
	"\n" +
	"\x10repository.proto\x12\x06gitter\"=\n" +
	"\fCommitDetail\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x19\n" +
	"\bpatch_id\x18\x02 \x01(\fR\apatchId\"A\n" +
	"\x0fRepositoryCache\x12.\n" +
	"\acommits\x18\x01 \x03(\v2\x14.gitter.CommitDetailR\acommits\"\x1c\n" +
	"\x06Commit\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"/\n" +
	"\x03Ref\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"\xa5\x01\n" +
	"\x17AffectedCommitsResponse\x12(\n" +
	"\acommits\x18\x01 \x03(\v2\x0e.gitter.CommitR\acommits\x12\x1f\n" +
	"\x04tags\x18\x02 \x03(\v2\v.gitter.RefR\x04tags\x12?\n" +
	"\x14cherry_picked_events\x18\x03 \x03(\v2\r.gitter.EventR\x12cherryPickedEvents\"/\n" +
	"\fTagsResponse\x12\x1f\n" +
	"\x04tags\x18\x01 \x03(\v2\v.gitter.RefR\x04tags\"M\n" +
	"\x05Event\x120\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x11.gitter.EventTypeR\teventType\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"C\n" +
	"\fCacheRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12!\n" +
	"\fforce_update\x18\x02 \x01(\bR\vforceUpdate\"\xe0\x02\n" +
	"\x16AffectedCommitsRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12%\n" +
	"\x06events\x18\x02 \x03(\v2\r.gitter.EventR\x06events\x12B\n" +
	"\x1ddetect_cherrypicks_introduced\x18\x03 \x01(\bR\x1bdetectCherrypicksIntroduced\x128\n" +
	"\x18detect_cherrypicks_fixed\x18\x04 \x01(\bR\x16detectCherrypicksFixed\x128\n" +
	"\x18detect_cherrypicks_limit\x18\x05 \x01(\bR\x16detectCherrypicksLimit\x12!\n" +
	"\fforce_update\x18\x06 \x01(\bR\vforceUpdate\x122\n" +
	"\x15consider_all_branches\x18\a \x01(\bR\x13considerAllBranches*D\n" +
	"\tEventType\x12\x0e\n" +
	"\n" +
	"INTRODUCED\x10\x00\x12\t\n" +
	"\x05FIXED\x10\x01\x12\x11\n" +
	"\rLAST_AFFECTED\x10\x02\x12\t\n" +
	"\x05LIMIT\x10\x03B\x0eZ\f./repositoryb\x06proto3"

var (
	file_repository_proto_rawDescOnce sync.Once
	file_repository_proto_rawDescData []byte
)

func file_repository_proto_rawDescGZIP() []byte {
	file_repository_proto_rawDescOnce.Do(func() {
		file_repository_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_proto_rawDesc), len(file_repository_proto_rawDesc)))
	})
	return file_repository_proto_rawDescData
}

var file_repository_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_repository_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_repository_proto_goTypes = []any{
	(EventType)(0),                  // 0: gitter.EventType
	(*CommitDetail)(nil),            // 1: gitter.CommitDetail
	(*RepositoryCache)(nil),         // 2: gitter.RepositoryCache
	(*Commit)(nil),                  // 3: gitter.Commit
	(*Ref)(nil),                     // 4: gitter.Ref
	(*AffectedCommitsResponse)(nil), // 5: gitter.AffectedCommitsResponse
	(*TagsResponse)(nil),            // 6: gitter.TagsResponse
	(*Event)(nil),                   // 7: gitter.Event
	(*CacheRequest)(nil),            // 8: gitter.CacheRequest
	(*AffectedCommitsRequest)(nil),  // 9: gitter.AffectedCommitsRequest
}
var file_repository_proto_depIdxs = []int32{
	1, // 0: gitter.RepositoryCache.commits:type_name -> gitter.CommitDetail
	3, // 1: gitter.AffectedCommitsResponse.commits:type_name -> gitter.Commit
	4, // 2: gitter.AffectedCommitsResponse.tags:type_name -> gitter.Ref
	7, // 3: gitter.AffectedCommitsResponse.cherry_picked_events:type_name -> gitter.Event
	4, // 4: gitter.TagsResponse.tags:type_name -> gitter.Ref
	0, // 5: gitter.Event.event_type:type_name -> gitter.EventType
	7, // 6: gitter.AffectedCommitsRequest.events:type_name -> gitter.Event
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_repository_proto_init() }
func file_repository_proto_init() {
	if File_repository_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_proto_rawDesc), len(file_repository_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repository_proto_goTypes,
		DependencyIndexes: file_repository_proto_depIdxs,
		EnumInfos:         file_repository_proto_enumTypes,
		MessageInfos:      file_repository_proto_msgTypes,
	}.Build()
	File_repository_proto = out.File
	file_repository_proto_goTypes = nil
	file_repository_proto_depIdxs = nil
}
