apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: osv-api
description: osv api pipeline
serialPipeline:
  stages:
  - targetId: staging
    profiles: [ staging ]
  - targetId: production
    profiles: [ prod ]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: oss-vdb-test api instance
run:
  location: projects/oss-vdb-test/locations/us-central1
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: deployment@oss-vdb.iam.gserviceaccount.com
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: oss-vdb api instance
run:
  location: projects/oss-vdb/locations/us-central1
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: deployment@oss-vdb.iam.gserviceaccount.com
