apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: osv-grpc-backend-batch
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containers:
      - image: osv-server
        resources:
          limits:
            memory: 4Gi
        startupProbe:
          grpc:
            service: osv.v1.OSV
        livenessProbe:
          grpc:
            service: osv.v1.OSV
          timeoutSeconds: 5
          failureThreshold: 3
          periodSeconds: 10
      timeoutSeconds: 60
      containerConcurrency: 1
