apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: osv-grpc-backend
spec:
  template:
    spec:
      containers:
      - image: osv-server
        resources:
          limits:
            memory: 4Gi
        startupProbe:
          grpc:
            service: osv.v1.OSV
        livenessProbe:
          grpc:
            service: osv.v1.OSV
      timeoutSeconds: 60
      containerConcurrency: 20
