apiVersion: skaffold/v3
kind: Config
metadata:
  name: gke-indexer
profiles:
- name: staging
  manifests:
    kustomize:
      paths:
      - environments/oss-vdb-test

- name: prod
  manifests:
    kustomize:
      paths:
      - environments/oss-vdb

deploy:
  kubectl: {}
