// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.5
// source: importfinding.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportFindingType int32

const (
	ImportFindingType_IMPORT_FINDING_TYPE_NONE             ImportFindingType = 0
	ImportFindingType_IMPORT_FINDING_TYPE_DELETED          ImportFindingType = 1
	ImportFindingType_IMPORT_FINDING_TYPE_INVALID_JSON     ImportFindingType = 2
	ImportFindingType_IMPORT_FINDING_TYPE_INVALID_PACKAGE  ImportFindingType = 3
	ImportFindingType_IMPORT_FINDING_TYPE_INVALID_PURL     ImportFindingType = 4
	ImportFindingType_IMPORT_FINDING_TYPE_INVALID_VERSION  ImportFindingType = 5
	ImportFindingType_IMPORT_FINDING_TYPE_INVALID_COMMIT   ImportFindingType = 6
	ImportFindingType_IMPORT_FINDING_TYPE_INVALID_RANGE    ImportFindingType = 7
	ImportFindingType_IMPORT_FINDING_TYPE_INVALID_RECORD   ImportFindingType = 8
	ImportFindingType_IMPORT_FINDING_TYPE_INVALID_ALIASES  ImportFindingType = 9
	ImportFindingType_IMPORT_FINDING_TYPE_INVALID_UPSTREAM ImportFindingType = 10
	ImportFindingType_IMPORT_FINDING_TYPE_INVALID_RELATED  ImportFindingType = 11
	ImportFindingType_IMPORT_FINDING_TYPE_BAD_ALIASED_CVE  ImportFindingType = 12
)

// Enum value maps for ImportFindingType.
var (
	ImportFindingType_name = map[int32]string{
		0:  "IMPORT_FINDING_TYPE_NONE",
		1:  "IMPORT_FINDING_TYPE_DELETED",
		2:  "IMPORT_FINDING_TYPE_INVALID_JSON",
		3:  "IMPORT_FINDING_TYPE_INVALID_PACKAGE",
		4:  "IMPORT_FINDING_TYPE_INVALID_PURL",
		5:  "IMPORT_FINDING_TYPE_INVALID_VERSION",
		6:  "IMPORT_FINDING_TYPE_INVALID_COMMIT",
		7:  "IMPORT_FINDING_TYPE_INVALID_RANGE",
		8:  "IMPORT_FINDING_TYPE_INVALID_RECORD",
		9:  "IMPORT_FINDING_TYPE_INVALID_ALIASES",
		10: "IMPORT_FINDING_TYPE_INVALID_UPSTREAM",
		11: "IMPORT_FINDING_TYPE_INVALID_RELATED",
		12: "IMPORT_FINDING_TYPE_BAD_ALIASED_CVE",
	}
	ImportFindingType_value = map[string]int32{
		"IMPORT_FINDING_TYPE_NONE":             0,
		"IMPORT_FINDING_TYPE_DELETED":          1,
		"IMPORT_FINDING_TYPE_INVALID_JSON":     2,
		"IMPORT_FINDING_TYPE_INVALID_PACKAGE":  3,
		"IMPORT_FINDING_TYPE_INVALID_PURL":     4,
		"IMPORT_FINDING_TYPE_INVALID_VERSION":  5,
		"IMPORT_FINDING_TYPE_INVALID_COMMIT":   6,
		"IMPORT_FINDING_TYPE_INVALID_RANGE":    7,
		"IMPORT_FINDING_TYPE_INVALID_RECORD":   8,
		"IMPORT_FINDING_TYPE_INVALID_ALIASES":  9,
		"IMPORT_FINDING_TYPE_INVALID_UPSTREAM": 10,
		"IMPORT_FINDING_TYPE_INVALID_RELATED":  11,
		"IMPORT_FINDING_TYPE_BAD_ALIASED_CVE":  12,
	}
)

func (x ImportFindingType) Enum() *ImportFindingType {
	p := new(ImportFindingType)
	*p = x
	return p
}

func (x ImportFindingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImportFindingType) Descriptor() protoreflect.EnumDescriptor {
	return file_importfinding_proto_enumTypes[0].Descriptor()
}

func (ImportFindingType) Type() protoreflect.EnumType {
	return &file_importfinding_proto_enumTypes[0]
}

func (x ImportFindingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImportFindingType.Descriptor instead.
func (ImportFindingType) EnumDescriptor() ([]byte, []int) {
	return file_importfinding_proto_rawDescGZIP(), []int{0}
}

// An importfinding entry.
// The protobuf representation is *NOT* stable and only used for implementing
// the JSON based API.
type ImportFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BugId         string                 `protobuf:"bytes,1,opt,name=bug_id,json=bugId,proto3" json:"bug_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Findings      []ImportFindingType    `protobuf:"varint,3,rep,packed,name=findings,proto3,enum=osv.ImportFindingType" json:"findings,omitempty"`
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastAttempt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_attempt,json=lastAttempt,proto3" json:"last_attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportFinding) Reset() {
	*x = ImportFinding{}
	mi := &file_importfinding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFinding) ProtoMessage() {}

func (x *ImportFinding) ProtoReflect() protoreflect.Message {
	mi := &file_importfinding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFinding.ProtoReflect.Descriptor instead.
func (*ImportFinding) Descriptor() ([]byte, []int) {
	return file_importfinding_proto_rawDescGZIP(), []int{0}
}

func (x *ImportFinding) GetBugId() string {
	if x != nil {
		return x.BugId
	}
	return ""
}

func (x *ImportFinding) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ImportFinding) GetFindings() []ImportFindingType {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *ImportFinding) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *ImportFinding) GetLastAttempt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAttempt
	}
	return nil
}

var File_importfinding_proto protoreflect.FileDescriptor

const file_importfinding_proto_rawDesc = "" +
	"\n" +
	"\x13importfinding.proto\x12\x03osv\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x01\n" +
	"\rImportFinding\x12\x15\n" +
	"\x06bug_id\x18\x01 \x01(\tR\x05bugId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x122\n" +
	"\bfindings\x18\x03 \x03(\x0e2\x16.osv.ImportFindingTypeR\bfindings\x129\n" +
	"\n" +
	"first_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x12=\n" +
	"\flast_attempt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastAttempt*\x8c\x04\n" +
	"\x11ImportFindingType\x12\x1c\n" +
	"\x18IMPORT_FINDING_TYPE_NONE\x10\x00\x12\x1f\n" +
	"\x1bIMPORT_FINDING_TYPE_DELETED\x10\x01\x12$\n" +
	" IMPORT_FINDING_TYPE_INVALID_JSON\x10\x02\x12'\n" +
	"#IMPORT_FINDING_TYPE_INVALID_PACKAGE\x10\x03\x12$\n" +
	" IMPORT_FINDING_TYPE_INVALID_PURL\x10\x04\x12'\n" +
	"#IMPORT_FINDING_TYPE_INVALID_VERSION\x10\x05\x12&\n" +
	"\"IMPORT_FINDING_TYPE_INVALID_COMMIT\x10\x06\x12%\n" +
	"!IMPORT_FINDING_TYPE_INVALID_RANGE\x10\a\x12&\n" +
	"\"IMPORT_FINDING_TYPE_INVALID_RECORD\x10\b\x12'\n" +
	"#IMPORT_FINDING_TYPE_INVALID_ALIASES\x10\t\x12(\n" +
	"$IMPORT_FINDING_TYPE_INVALID_UPSTREAM\x10\n" +
	"\x12'\n" +
	"#IMPORT_FINDING_TYPE_INVALID_RELATED\x10\v\x12'\n" +
	"#IMPORT_FINDING_TYPE_BAD_ALIASED_CVE\x10\fB\"Z osv.dev/bindings/go/internal/apib\x06proto3"

var (
	file_importfinding_proto_rawDescOnce sync.Once
	file_importfinding_proto_rawDescData []byte
)

func file_importfinding_proto_rawDescGZIP() []byte {
	file_importfinding_proto_rawDescOnce.Do(func() {
		file_importfinding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_importfinding_proto_rawDesc), len(file_importfinding_proto_rawDesc)))
	})
	return file_importfinding_proto_rawDescData
}

var file_importfinding_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_importfinding_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_importfinding_proto_goTypes = []any{
	(ImportFindingType)(0),        // 0: osv.ImportFindingType
	(*ImportFinding)(nil),         // 1: osv.ImportFinding
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_importfinding_proto_depIdxs = []int32{
	0, // 0: osv.ImportFinding.findings:type_name -> osv.ImportFindingType
	2, // 1: osv.ImportFinding.first_seen:type_name -> google.protobuf.Timestamp
	2, // 2: osv.ImportFinding.last_attempt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_importfinding_proto_init() }
func file_importfinding_proto_init() {
	if File_importfinding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_importfinding_proto_rawDesc), len(file_importfinding_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_importfinding_proto_goTypes,
		DependencyIndexes: file_importfinding_proto_depIdxs,
		EnumInfos:         file_importfinding_proto_enumTypes,
		MessageInfos:      file_importfinding_proto_msgTypes,
	}.Build()
	File_importfinding_proto = out.File
	file_importfinding_proto_goTypes = nil
	file_importfinding_proto_depIdxs = nil
}
