apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: osv-monitoring
  annotations:
    iam.gke.io/gcp-service-account: osv-monitoring-sa@oss-vdb-test.iam.gserviceaccount.com
