[[IgnoredVulns]]
id = "GO-2022-0968"
# ignoreUntil = 2022-11-09 # Optional exception expiry date
reason = "No ssh servers are connected to or hosted in Go lang"

[[IgnoredVulns]]
id = "GO-2022-1059"
# ignoreUntil = 2022-11-09 # Optional exception expiry date
reason = "No external http servers are written in Go lang."

[[IgnoredVulns]]
id = "GO-2022-0356"
# ignoreUntil = 2022-11-09 # Optional exception expiry date
reason = "No ssh servers"

[[IgnoredVulns]]
id = "GO-2022-0969"
# ignoreUntil = 2022-11-09 # Optional exception expiry date
reason = "No external http servers in Go lang."
