apiVersion: batch/v1
kind: CronJob
metadata:
  name: exporter
  labels:
    cronLastSuccessfulTimeMins: "30"
spec:
  timeZone: "Australia/Sydney"
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  # If the previous job overruns by more than a minute,
  # Don't try to immediately queue up the next job
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: exporter
            image: exporter
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: "/scratch"
              name: "scratch-volume"
            resources:
              requests:
                cpu: "4"
                memory: "4G"
                ephemeral-storage: "35G"
              limits:
                cpu: "7"
                memory: "8G"
                ephemeral-storage: "50G"
            env:
              - name: TRACE_SAMPLE_RATE
                value: "0.0"
              - name: SCRATCH_DIR
                value: "/scratch"
          volumes:
          - name: "scratch-volume"
            emptyDir:
              sizeLimit: "50G"
          restartPolicy: Never
