apiVersion: batch/v1
kind: CronJob
metadata:
  name: exporter
  labels:
    cronLastSuccessfulTimeMins: "30"
spec:
  timeZone: "Australia/Sydney"
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  # If the previous job overruns by more than a minute,
  # Don't try to immediately queue up the next job
  startingDeadlineSeconds: 60
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
          - key: workloadType
            operator: Equal
            value: highend
          nodeSelector:
            cloud.google.com/gke-nodepool: highend
          containers:
          - name: exporter
            image: exporter
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: "/scratch"
              name: "scratch-volume"
            resources:
              requests:
                cpu: "8"
                memory: "30G"
                ephemeral-storage: "35G"
              limits:
                cpu: "16"
                memory: "60G"
                ephemeral-storage: "50G"
            env:
              - name: TRACE_SAMPLE_RATE
                value: "0.0"
              - name: SCRATCH_DIR
                value: "/scratch"
              - name: GOMEMLIMIT
                value: "50GiB"
          volumes:
          - name: "scratch-volume"
            emptyDir:
              sizeLimit: "50G"
          restartPolicy: Never
