apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-workers
description: worker, importer, exporter pipeline
serialPipeline:
  stages:
  - targetId: staging-workers
    profiles: [ staging ]
  - targetId: production-workers
    profiles: [ prod ]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging-workers
description: oss-vdb-test worker cluster
gke:
  cluster: projects/oss-vdb-test/locations/us-central1-f/clusters/workers
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: deployment@oss-vdb.iam.gserviceaccount.com
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production-workers
description: oss-vdb worker cluster
gke:
  cluster: projects/oss-vdb/locations/us-central1-f/clusters/workers
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: deployment@oss-vdb.iam.gserviceaccount.com
