apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: gke-workers
description: worker, importer, exporter pipeline
serialPipeline:
 stages:
 - targetId: staging
   profiles: [ staging ]
 - targetId: production
   profiles: [ prod ]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: staging
description: oss-vdb-test worker cluster
gke:
 cluster: projects/oss-vdb-test/locations/us-central1-f/clusters/workers
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: production
description: oss-vdb worker cluster
gke:
 cluster: projects/oss-vdb/locations/us-central1-f/clusters/workers