apiVersion: skaffold/v2beta16
kind: Config
metadata:
 name: gke-workers
profiles:
 - name: staging
   deploy:
     kustomize:
       paths:
         - environments/oss-vdb-test
 - name: prod
   deploy:
     kustomize:
       paths:
         - environments/oss-vdb