apiVersion: skaffold/v3
kind: Config
metadata:
  name: gke-workers
profiles:
- name: staging
  deploy:
    kustomize:
      paths:
      - environments/oss-vdb-test

- name: prod
  deploy:
    kustomize:
      paths:
      - environments/oss-vdb
