apiVersion: batch/v1
kind: CronJob
metadata:
  name: nvd-mirror
  labels:
    cronLastSuccessfulTimeMins: "240"
spec:
  timeZone: "Australia/Sydney"
  schedule: "5 */2 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          containers:
          - name: nvd-mirror
            args:
            - "--gcs-bucket"
            - "$(BUCKET)"
            image: nvd-mirror
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "1"
                memory: "1G"
              limits:
                cpu: "2"
                memory: "2G"
          restartPolicy: Never
