#!/bin/bash -ex

if [ $# -lt 3 ]; then
  echo "Usage: $0 <project-id> <API> <Cloud Run service name> <api_config.yaml>"
  exit 1
fi

project_id=$1
api=$2
service=$3
api_config=$4
this_dir=$(dirname "$(readlink -f "$0")")

gcloud endpoints services deploy api_descriptor.pb $api_config --project=$project_id
config_id=$(curl -H "Authorization: Bearer $(gcloud auth print-access-token)" \
            https://servicemanagement.googleapis.com/v1/services/$api/configs | \
            jq -r '.serviceConfigs[0].id')
echo Deploying for $config_id

image_tag=$($this_dir/build_esp_image -s $api -p $project_id -c $config_id | grep "IMAGE:" | cut -f2 -d' ')
gcloud run deploy $service \
  --allow-unauthenticated \
  --set-env-vars=ESPv2_ARGS=^++^--transcoding_preserve_proto_field_names++--envoy_connection_buffer_limit_bytes=10485760 \
  --platform managed \
  --project=$project_id \
  --region=us-central1 \
  --image="$image_tag"
