# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM gcr.io/endpoints-release/endpoints-runtime:2

USER root

# Context: https://github.com/mhart/alpine-node/issues/48#issuecomment-370171836
# The UID needs to be set to 1000 in order to map files without permission issues.
RUN addgroup -g 1000 -S osv && \
    adduser --no-create-home -u 1000 -S osv -G osv

USER osv
