"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _ImportFindingType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ImportFindingTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ImportFindingType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    IMPORT_FINDING_TYPE_NONE: _ImportFindingType.ValueType  # 0
    IMPORT_FINDING_TYPE_DELETED: _ImportFindingType.ValueType  # 1
    IMPORT_FINDING_TYPE_INVALID_JSON: _ImportFindingType.ValueType  # 2
    IMPORT_FINDING_TYPE_INVALID_PACKAGE: _ImportFindingType.ValueType  # 3
    IMPORT_FINDING_TYPE_INVALID_PURL: _ImportFindingType.ValueType  # 4
    IMPORT_FINDING_TYPE_INVALID_VERSION: _ImportFindingType.ValueType  # 5
    IMPORT_FINDING_TYPE_INVALID_COMMIT: _ImportFindingType.ValueType  # 6
    IMPORT_FINDING_TYPE_INVALID_RANGE: _ImportFindingType.ValueType  # 7
    IMPORT_FINDING_TYPE_INVALID_RECORD: _ImportFindingType.ValueType  # 8
    IMPORT_FINDING_TYPE_INVALID_ALIASES: _ImportFindingType.ValueType  # 9
    IMPORT_FINDING_TYPE_INVALID_UPSTREAM: _ImportFindingType.ValueType  # 10
    IMPORT_FINDING_TYPE_INVALID_RELATED: _ImportFindingType.ValueType  # 11
    IMPORT_FINDING_TYPE_BAD_ALIASED_CVE: _ImportFindingType.ValueType  # 12

class ImportFindingType(_ImportFindingType, metaclass=_ImportFindingTypeEnumTypeWrapper): ...

IMPORT_FINDING_TYPE_NONE: ImportFindingType.ValueType  # 0
IMPORT_FINDING_TYPE_DELETED: ImportFindingType.ValueType  # 1
IMPORT_FINDING_TYPE_INVALID_JSON: ImportFindingType.ValueType  # 2
IMPORT_FINDING_TYPE_INVALID_PACKAGE: ImportFindingType.ValueType  # 3
IMPORT_FINDING_TYPE_INVALID_PURL: ImportFindingType.ValueType  # 4
IMPORT_FINDING_TYPE_INVALID_VERSION: ImportFindingType.ValueType  # 5
IMPORT_FINDING_TYPE_INVALID_COMMIT: ImportFindingType.ValueType  # 6
IMPORT_FINDING_TYPE_INVALID_RANGE: ImportFindingType.ValueType  # 7
IMPORT_FINDING_TYPE_INVALID_RECORD: ImportFindingType.ValueType  # 8
IMPORT_FINDING_TYPE_INVALID_ALIASES: ImportFindingType.ValueType  # 9
IMPORT_FINDING_TYPE_INVALID_UPSTREAM: ImportFindingType.ValueType  # 10
IMPORT_FINDING_TYPE_INVALID_RELATED: ImportFindingType.ValueType  # 11
IMPORT_FINDING_TYPE_BAD_ALIASED_CVE: ImportFindingType.ValueType  # 12
Global___ImportFindingType: _TypeAlias = ImportFindingType  # noqa: Y015

@_typing.final
class ImportFinding(_message.Message):
    """An importfinding entry.
    The protobuf representation is *NOT* stable and only used for implementing
    the JSON based API.
    """

    DESCRIPTOR: _descriptor.Descriptor

    BUG_ID_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    FINDINGS_FIELD_NUMBER: _builtins.int
    FIRST_SEEN_FIELD_NUMBER: _builtins.int
    LAST_ATTEMPT_FIELD_NUMBER: _builtins.int
    bug_id: _builtins.str
    source: _builtins.str
    @_builtins.property
    def findings(self) -> _containers.RepeatedScalarFieldContainer[Global___ImportFindingType.ValueType]: ...
    @_builtins.property
    def first_seen(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def last_attempt(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        bug_id: _builtins.str = ...,
        source: _builtins.str = ...,
        findings: _abc.Iterable[Global___ImportFindingType.ValueType] | None = ...,
        first_seen: _timestamp_pb2.Timestamp | None = ...,
        last_attempt: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["first_seen", b"first_seen", "last_attempt", b"last_attempt"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bug_id", b"bug_id", "findings", b"findings", "first_seen", b"first_seen", "last_attempt", b"last_attempt", "source", b"source"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ImportFinding: _TypeAlias = ImportFinding  # noqa: Y015
