# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osv_service_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osv import vulnerability_pb2 as osv_dot_vulnerability__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='osv_service_v1.proto',
  package='osv.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14osv_service_v1.proto\x12\x06osv.v1\x1a\x17osv/vulnerability.proto\x1a\x1cgoogle/api/annotations.proto\"6\n\x11VulnerabilityList\x12!\n\x05vulns\x18\x01 \x03(\x0b\x32\x12.osv.Vulnerability\"T\n\x05Query\x12\x10\n\x06\x63ommit\x18\x01 \x01(\tH\x00\x12\x11\n\x07version\x18\x02 \x01(\tH\x00\x12\x1d\n\x07package\x18\x04 \x01(\x0b\x32\x0c.osv.PackageB\x07\n\x05param\"#\n\x15GetVulnByIdParameters\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x17QueryAffectedParameters\x12\x1c\n\x05query\x18\x01 \x01(\x0b\x32\r.osv.v1.Query2\x93\x03\n\x03OSV\x12X\n\x0bGetVulnById\x12\x1d.osv.v1.GetVulnByIdParameters\x1a\x12.osv.Vulnerability\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/vulns/{id}\x12\x65\n\rQueryAffected\x12\x1f.osv.v1.QueryAffectedParameters\x1a\x19.osv.v1.VulnerabilityList\"\x18\x82\xd3\xe4\x93\x02\x12\"\t/v1/query:\x05query\x12^\n\x0eGetVulnByIdNew\x12\x1d.osv.v1.GetVulnByIdParameters\x1a\x12.osv.Vulnerability\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1new/vulns/{id}\x12k\n\x10QueryAffectedNew\x12\x1f.osv.v1.QueryAffectedParameters\x1a\x19.osv.v1.VulnerabilityList\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x0c/v1new/query:\x05queryb\x06proto3'
  ,
  dependencies=[osv_dot_vulnerability__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_VULNERABILITYLIST = _descriptor.Descriptor(
  name='VulnerabilityList',
  full_name='osv.v1.VulnerabilityList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vulns', full_name='osv.v1.VulnerabilityList.vulns', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=141,
)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='osv.v1.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commit', full_name='osv.v1.Query.commit', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='osv.v1.Query.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='package', full_name='osv.v1.Query.package', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='param', full_name='osv.v1.Query.param',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=143,
  serialized_end=227,
)


_GETVULNBYIDPARAMETERS = _descriptor.Descriptor(
  name='GetVulnByIdParameters',
  full_name='osv.v1.GetVulnByIdParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='osv.v1.GetVulnByIdParameters.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=264,
)


_QUERYAFFECTEDPARAMETERS = _descriptor.Descriptor(
  name='QueryAffectedParameters',
  full_name='osv.v1.QueryAffectedParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='osv.v1.QueryAffectedParameters.query', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=321,
)

_VULNERABILITYLIST.fields_by_name['vulns'].message_type = osv_dot_vulnerability__pb2._VULNERABILITY
_QUERY.fields_by_name['package'].message_type = osv_dot_vulnerability__pb2._PACKAGE
_QUERY.oneofs_by_name['param'].fields.append(
  _QUERY.fields_by_name['commit'])
_QUERY.fields_by_name['commit'].containing_oneof = _QUERY.oneofs_by_name['param']
_QUERY.oneofs_by_name['param'].fields.append(
  _QUERY.fields_by_name['version'])
_QUERY.fields_by_name['version'].containing_oneof = _QUERY.oneofs_by_name['param']
_QUERYAFFECTEDPARAMETERS.fields_by_name['query'].message_type = _QUERY
DESCRIPTOR.message_types_by_name['VulnerabilityList'] = _VULNERABILITYLIST
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['GetVulnByIdParameters'] = _GETVULNBYIDPARAMETERS
DESCRIPTOR.message_types_by_name['QueryAffectedParameters'] = _QUERYAFFECTEDPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VulnerabilityList = _reflection.GeneratedProtocolMessageType('VulnerabilityList', (_message.Message,), {
  'DESCRIPTOR' : _VULNERABILITYLIST,
  '__module__' : 'osv_service_v1_pb2'
  # @@protoc_insertion_point(class_scope:osv.v1.VulnerabilityList)
  })
_sym_db.RegisterMessage(VulnerabilityList)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'osv_service_v1_pb2'
  # @@protoc_insertion_point(class_scope:osv.v1.Query)
  })
_sym_db.RegisterMessage(Query)

GetVulnByIdParameters = _reflection.GeneratedProtocolMessageType('GetVulnByIdParameters', (_message.Message,), {
  'DESCRIPTOR' : _GETVULNBYIDPARAMETERS,
  '__module__' : 'osv_service_v1_pb2'
  # @@protoc_insertion_point(class_scope:osv.v1.GetVulnByIdParameters)
  })
_sym_db.RegisterMessage(GetVulnByIdParameters)

QueryAffectedParameters = _reflection.GeneratedProtocolMessageType('QueryAffectedParameters', (_message.Message,), {
  'DESCRIPTOR' : _QUERYAFFECTEDPARAMETERS,
  '__module__' : 'osv_service_v1_pb2'
  # @@protoc_insertion_point(class_scope:osv.v1.QueryAffectedParameters)
  })
_sym_db.RegisterMessage(QueryAffectedParameters)



_OSV = _descriptor.ServiceDescriptor(
  name='OSV',
  full_name='osv.v1.OSV',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=324,
  serialized_end=727,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetVulnById',
    full_name='osv.v1.OSV.GetVulnById',
    index=0,
    containing_service=None,
    input_type=_GETVULNBYIDPARAMETERS,
    output_type=osv_dot_vulnerability__pb2._VULNERABILITY,
    serialized_options=b'\202\323\344\223\002\020\022\016/v1/vulns/{id}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryAffected',
    full_name='osv.v1.OSV.QueryAffected',
    index=1,
    containing_service=None,
    input_type=_QUERYAFFECTEDPARAMETERS,
    output_type=_VULNERABILITYLIST,
    serialized_options=b'\202\323\344\223\002\022\"\t/v1/query:\005query',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetVulnByIdNew',
    full_name='osv.v1.OSV.GetVulnByIdNew',
    index=2,
    containing_service=None,
    input_type=_GETVULNBYIDPARAMETERS,
    output_type=osv_dot_vulnerability__pb2._VULNERABILITY,
    serialized_options=b'\202\323\344\223\002\023\022\021/v1new/vulns/{id}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryAffectedNew',
    full_name='osv.v1.OSV.QueryAffectedNew',
    index=3,
    containing_service=None,
    input_type=_QUERYAFFECTEDPARAMETERS,
    output_type=_VULNERABILITYLIST,
    serialized_options=b'\202\323\344\223\002\025\"\014/v1new/query:\005query',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OSV)

DESCRIPTOR.services_by_name['OSV'] = _OSV

# @@protoc_insertion_point(module_scope)
