# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import osv_service_pb2 as osv__service__pb2


class OSVStub(object):
    """Open source vulnerability database.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBugById = channel.unary_unary(
                '/osv.OSV/GetBugById',
                request_serializer=osv__service__pb2.GetBugByIdParameters.SerializeToString,
                response_deserializer=osv__service__pb2.Bug.FromString,
                )
        self.QueryAffected = channel.unary_unary(
                '/osv.OSV/QueryAffected',
                request_serializer=osv__service__pb2.QueryAffectedParameters.SerializeToString,
                response_deserializer=osv__service__pb2.BugList.FromString,
                )
        self.QueryAffectedByCommit = channel.unary_unary(
                '/osv.OSV/QueryAffectedByCommit',
                request_serializer=osv__service__pb2.QueryAffectedByCommitParameters.SerializeToString,
                response_deserializer=osv__service__pb2.BugList.FromString,
                )


class OSVServicer(object):
    """Open source vulnerability database.
    """

    def GetBugById(self, request, context):
        """Return a `Bug` object for a given OSV ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAffected(self, request, context):
        """Query bugs for a particular project at a given commit or version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAffectedByCommit(self, request, context):
        """Query bugs for across all projects at a given commit. Since git SHAs should
        be unique, this is provided as a convenience over the project qualified
        endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OSVServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBugById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBugById,
                    request_deserializer=osv__service__pb2.GetBugByIdParameters.FromString,
                    response_serializer=osv__service__pb2.Bug.SerializeToString,
            ),
            'QueryAffected': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAffected,
                    request_deserializer=osv__service__pb2.QueryAffectedParameters.FromString,
                    response_serializer=osv__service__pb2.BugList.SerializeToString,
            ),
            'QueryAffectedByCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAffectedByCommit,
                    request_deserializer=osv__service__pb2.QueryAffectedByCommitParameters.FromString,
                    response_serializer=osv__service__pb2.BugList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'osv.OSV', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OSV(object):
    """Open source vulnerability database.
    """

    @staticmethod
    def GetBugById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/osv.OSV/GetBugById',
            osv__service__pb2.GetBugByIdParameters.SerializeToString,
            osv__service__pb2.Bug.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryAffected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/osv.OSV/QueryAffected',
            osv__service__pb2.QueryAffectedParameters.SerializeToString,
            osv__service__pb2.BugList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryAffectedByCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/osv.OSV/QueryAffectedByCommit',
            osv__service__pb2.QueryAffectedByCommitParameters.SerializeToString,
            osv__service__pb2.BugList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
