"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2021 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import importfinding_pb2 as _importfinding_pb2
import sys
import typing as _typing
import vulnerability_pb2 as _vulnerability_pb2

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class VulnerabilityList(_message.Message):
    """A list of Vulnerability entries."""

    DESCRIPTOR: _descriptor.Descriptor

    VULNS_FIELD_NUMBER: _builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    next_page_token: _builtins.str
    @_builtins.property
    def vulns(self) -> _containers.RepeatedCompositeFieldContainer[_vulnerability_pb2.Vulnerability]: ...
    def __init__(
        self,
        *,
        vulns: _abc.Iterable[_vulnerability_pb2.Vulnerability] | None = ...,
        next_page_token: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["next_page_token", b"next_page_token", "vulns", b"vulns"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VulnerabilityList: _TypeAlias = VulnerabilityList  # noqa: Y015

@_typing.final
class BatchVulnerabilityList(_message.Message):
    """Batched lists of Vulnerability entries."""

    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___VulnerabilityList]: ...
    def __init__(
        self,
        *,
        results: _abc.Iterable[Global___VulnerabilityList] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BatchVulnerabilityList: _TypeAlias = BatchVulnerabilityList  # noqa: Y015

@_typing.final
class Query(_message.Message):
    """Query format."""

    DESCRIPTOR: _descriptor.Descriptor

    COMMIT_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    PACKAGE_FIELD_NUMBER: _builtins.int
    PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    commit: _builtins.str
    """The commit hash to query for. If specified, `version` should not be set."""
    version: _builtins.str
    """The version string to query for. A fuzzy match is done against upstream
    versions. If specified, `commit` should not be set.
    """
    page_token: _builtins.str
    @_builtins.property
    def package(self) -> _vulnerability_pb2.Package:
        """The package to query against. When a `commit` hash is given, this is
        optional.
        """

    def __init__(
        self,
        *,
        commit: _builtins.str = ...,
        version: _builtins.str = ...,
        package: _vulnerability_pb2.Package | None = ...,
        page_token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "package", b"package", "param", b"param", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit", "package", b"package", "page_token", b"page_token", "param", b"param", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_param: _TypeAlias = _typing.Literal["commit", "version"]  # noqa: Y015
    _WhichOneofArgType_param: _TypeAlias = _typing.Literal["param", b"param"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_param) -> _WhichOneofReturnType_param | None: ...

Global___Query: _TypeAlias = Query  # noqa: Y015

@_typing.final
class BatchQuery(_message.Message):
    """Batch query format."""

    DESCRIPTOR: _descriptor.Descriptor

    QUERIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def queries(self) -> _containers.RepeatedCompositeFieldContainer[Global___Query]:
        """The queries that form this batch query."""

    def __init__(
        self,
        *,
        queries: _abc.Iterable[Global___Query] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["queries", b"queries"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BatchQuery: _TypeAlias = BatchQuery  # noqa: Y015

@_typing.final
class GetVulnByIdParameters(_message.Message):
    """Parameters for GetBugById."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetVulnByIdParameters: _TypeAlias = GetVulnByIdParameters  # noqa: Y015

@_typing.final
class QueryAffectedParameters(_message.Message):
    """Parameters for QueryAffected."""

    DESCRIPTOR: _descriptor.Descriptor

    QUERY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def query(self) -> Global___Query: ...
    def __init__(
        self,
        *,
        query: Global___Query | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["query", b"query"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["query", b"query"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAffectedParameters: _TypeAlias = QueryAffectedParameters  # noqa: Y015

@_typing.final
class QueryAffectedBatchParameters(_message.Message):
    """Parameters for QueryAffectedBatch."""

    DESCRIPTOR: _descriptor.Descriptor

    QUERY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def query(self) -> Global___BatchQuery: ...
    def __init__(
        self,
        *,
        query: Global___BatchQuery | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["query", b"query"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["query", b"query"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryAffectedBatchParameters: _TypeAlias = QueryAffectedBatchParameters  # noqa: Y015

@_typing.final
class DetermineVersionParameters(_message.Message):
    """Parameters for DetermineVersion."""

    DESCRIPTOR: _descriptor.Descriptor

    QUERY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def query(self) -> Global___VersionQuery: ...
    def __init__(
        self,
        *,
        query: Global___VersionQuery | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["query", b"query"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["query", b"query"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DetermineVersionParameters: _TypeAlias = DetermineVersionParameters  # noqa: Y015

@_typing.final
class ImportFindingsParameters(_message.Message):
    """Parameters for ImportFindings."""

    DESCRIPTOR: _descriptor.Descriptor

    SOURCE_FIELD_NUMBER: _builtins.int
    source: _builtins.str
    def __init__(
        self,
        *,
        source: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["source", b"source"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ImportFindingsParameters: _TypeAlias = ImportFindingsParameters  # noqa: Y015

@_typing.final
class VersionQuery(_message.Message):
    """The version query."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    FILE_HASHES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """The name of the dependency. Can be empty."""
    @_builtins.property
    def file_hashes(self) -> _containers.RepeatedCompositeFieldContainer[Global___FileHash]: ...
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        file_hashes: _abc.Iterable[Global___FileHash] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file_hashes", b"file_hashes", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VersionQuery: _TypeAlias = VersionQuery  # noqa: Y015

@_typing.final
class FileHash(_message.Message):
    """Information about the files in the repository
    to identify the version.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _HashType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _HashTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[FileHash._HashType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        MD5: FileHash._HashType.ValueType  # 0

    class HashType(_HashType, metaclass=_HashTypeEnumTypeWrapper): ...
    MD5: FileHash.HashType.ValueType  # 0

    FILE_PATH_FIELD_NUMBER: _builtins.int
    HASH_TYPE_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    file_path: _builtins.str
    """The file path inside the repository, relative to the repository root."""
    hash_type: Global___FileHash.HashType.ValueType
    hash: _builtins.bytes
    def __init__(
        self,
        *,
        file_path: _builtins.str = ...,
        hash_type: Global___FileHash.HashType.ValueType = ...,
        hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file_path", b"file_path", "hash", b"hash", "hash_type", b"hash_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FileHash: _TypeAlias = FileHash  # noqa: Y015

@_typing.final
class VersionMatchList(_message.Message):
    """Result of DetmineVersion."""

    DESCRIPTOR: _descriptor.Descriptor

    MATCHES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def matches(self) -> _containers.RepeatedCompositeFieldContainer[Global___VersionMatch]: ...
    def __init__(
        self,
        *,
        matches: _abc.Iterable[Global___VersionMatch] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["matches", b"matches"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VersionMatchList: _TypeAlias = VersionMatchList  # noqa: Y015

@_typing.final
class ImportFindingList(_message.Message):
    """Result of ImportFindings."""

    DESCRIPTOR: _descriptor.Descriptor

    INVALID_RECORDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def invalid_records(self) -> _containers.RepeatedCompositeFieldContainer[_importfinding_pb2.ImportFinding]: ...
    def __init__(
        self,
        *,
        invalid_records: _abc.Iterable[_importfinding_pb2.ImportFinding] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["invalid_records", b"invalid_records"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ImportFindingList: _TypeAlias = ImportFindingList  # noqa: Y015

@_typing.final
class VersionMatch(_message.Message):
    """Match information for the provided VersionQuery."""

    DESCRIPTOR: _descriptor.Descriptor

    SCORE_FIELD_NUMBER: _builtins.int
    REPO_INFO_FIELD_NUMBER: _builtins.int
    OSV_IDENTIFIER_FIELD_NUMBER: _builtins.int
    CPE23_FIELD_NUMBER: _builtins.int
    MINIMUM_FILE_MATCHES_FIELD_NUMBER: _builtins.int
    ESTIMATED_DIFF_FILES_FIELD_NUMBER: _builtins.int
    score: _builtins.float
    """Score in the interval (0.0, 1.0] with 1.0 being a perfect match."""
    cpe23: _builtins.str
    """CPE 2.3."""
    minimum_file_matches: _builtins.int
    """Definite number of files that have matched."""
    estimated_diff_files: _builtins.int
    """Estimated number of files that are different."""
    @_builtins.property
    def repo_info(self) -> Global___VersionRepositoryInformation:
        """Information about the upstream repository."""

    @_builtins.property
    def osv_identifier(self) -> _vulnerability_pb2.Package:
        """The OSV identifier."""

    def __init__(
        self,
        *,
        score: _builtins.float = ...,
        repo_info: Global___VersionRepositoryInformation | None = ...,
        osv_identifier: _vulnerability_pb2.Package | None = ...,
        cpe23: _builtins.str = ...,
        minimum_file_matches: _builtins.int = ...,
        estimated_diff_files: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["osv_identifier", b"osv_identifier", "repo_info", b"repo_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cpe23", b"cpe23", "estimated_diff_files", b"estimated_diff_files", "minimum_file_matches", b"minimum_file_matches", "osv_identifier", b"osv_identifier", "repo_info", b"repo_info", "score", b"score"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VersionMatch: _TypeAlias = VersionMatch  # noqa: Y015

@_typing.final
class VersionRepositoryInformation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _RepoType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _RepoTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[VersionRepositoryInformation._RepoType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNSPECIFIED: VersionRepositoryInformation._RepoType.ValueType  # 0
        GIT: VersionRepositoryInformation._RepoType.ValueType  # 1

    class RepoType(_RepoType, metaclass=_RepoTypeEnumTypeWrapper): ...
    UNSPECIFIED: VersionRepositoryInformation.RepoType.ValueType  # 0
    GIT: VersionRepositoryInformation.RepoType.ValueType  # 1

    TYPE_FIELD_NUMBER: _builtins.int
    ADDRESS_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    type: Global___VersionRepositoryInformation.RepoType.ValueType
    address: _builtins.str
    """Source address of the repository."""
    tag: _builtins.str
    """Commit tag"""
    version: _builtins.str
    """Parsed version from commit tag"""
    commit: _builtins.str
    """Commit hash hex."""
    def __init__(
        self,
        *,
        type: Global___VersionRepositoryInformation.RepoType.ValueType = ...,
        address: _builtins.str = ...,
        tag: _builtins.str = ...,
        version: _builtins.str = ...,
        commit: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "commit", b"commit", "tag", b"tag", "type", b"type", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___VersionRepositoryInformation: _TypeAlias = VersionRepositoryInformation  # noqa: Y015
