name: Renovate Config Validator

permissions: {}

on:
  push:
    branches: [ master ]
    paths:
      - 'renovate.json'
  pull_request:
    branches: [ master ]
    paths:
      - 'renovate.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Nodes.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '^24'

      - name: Validate Renovate Config
        run: npx --yes --package renovate -- renovate-config-validator
